[package]
name = "tull-rust"
version = "0.1.0"
edition = "2018"

[dependencies]
structopt = "0.3.13"
home = "0.5.3"
uuid = { version = "0.8", features = ["v4"] }
tokio = { version = "1", features = ["full"] }
warp = "0.3.1"
subprocess = "0.2.7"
serde_derive = "1.0"
serde = "1.0"
